### NumPy

  - NumPy
    - NumPy는 Python 라이브러리입니다.
    - NumPy는 배열을 다루는 데 사용됩니다.
    - NumPy는 "수치형 파이썬"의 약자입니다.

In [1]:
# NumPy 배열을 만듭니다.
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


- NumPy란 무엇인가요?
  - NumPy는 배열 작업에 사용되는 Python 라이브러리입니다.
  - 선형 대수, 푸리에 변환, 행렬의 영역에서 작업하는 함수도 제공합니다.
  - NumPy는 2005년 Travis Oliphant에 의해 개발되었습니다. 오픈 소스 프로젝트이며 무료로 사용할 수 있습니다.
  - NumPy는 Numerical Python의 약자입니다.

- NumPy를 사용해야 하는 이유
  - Python에는 배열의 역할을 하는 리스트가 있지만, 처리 속도가 느립니다.
  - NumPy는 기존 Python 리스트보다 최대 50배 빠른 배열 객체를 제공하는 것을 목표로 합니다.
  - NumPy의 배열 객체는 ndarray이며, ndarray 작업을 매우 쉽게 해주는 다양한 지원 함수를 제공합니다.
  - 배열은 속도와 리소스가 매우 중요한 데이터 과학에서 매우 자주 사용됩니다.
  
- 데이터 과학: 데이터를 저장하고, 사용하고, 분석하여 정보를 도출하는 방법을 연구하는 컴퓨터 과학의 한 분야입니다.
  
- NumPy가 리스트보다 빠른 이유는 무엇일까요?
  - NumPy 배열은 리스트와 달리 메모리의 한 연속된 위치에 저장되므로 프로세스가 매우 효율적으로 접근하고 조작할 수 있습니다.
  - 이러한 동작을 컴퓨터 과학에서는 참조 지역성이라고 합니다.
  - 이것이 NumPy가 리스트보다 빠른 주된 이유입니다. 또한 최신 CPU 아키텍처에서 작동하도록 최적화되어 있습니다.

- NumPy는 어떤 언어로 작성되었나요?
  - NumPy는 Python 라이브러리이며 일부는 Python으로 작성되었지만, 빠른 계산이 필요한 대부분의 부분은 C 또는 C++로 작성되었습니다.

- NumPy 코드베이스는 어디에 있나요?
  - NumPy 소스 코드는 이 github 저장소(https://github.com/numpy/numpy)에 있습니다.

- github: 여러 사람이 동일한 코드베이스에서 작업할 수 있도록 합니다.

- NumPy 설치
  - Python과 PIP가 시스템에 이미 설치되어 있다면 NumPy 설치는 매우 쉽습니다.
  - 다음 명령어를 사용하여 설치하세요.
    ```bash
    pip install numpy
    ```
  - 이 명령이 실패하면 Anaconda, Spyder 등 NumPy가 이미 설치된 Python 배포판을 사용하세요.
  
- NumPy 가져오기
  - NumPy가 설치되면 import 키워드를 추가하여 애플리케이션에 가져오세요.
    ```python
    import numpy
    ```
  - 이제 NumPy를 가져와서 사용할 준비가 되었습니다.

In [2]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


- NumPy를 np로 가져오기
  - NumPy는 일반적으로 np 별칭으로 가져옵니다.
  - 별칭: Python에서 별칭은 동일한 것을 지칭하는 다른 이름입니다.
  - 가져올 때 as 키워드를 사용하여 별칭을 만듭니다.
    ```python
    import numpy as np
    ```
  - 이제 NumPy 패키지는 numpy 대신 np라고 불릴 수 있습니다.

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


- NumPy 버전 확인
  - 버전 문자열은 `__version__` 속성에 저장됩니다.

In [4]:
import numpy as np

print(np.__version__)

2.3.1


- NumPy ndarray 객체 만들기
  - NumPy는 배열을 다루는 데 사용됩니다. NumPy의 배열 객체는 ndarray입니다.
  - array() 함수를 사용하여 NumPy ndarray 객체를 만들 수 있습니다.

In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

# type(): 이 Python 내장 함수는 전달된 객체의 타입을 알려줍니다. 위 코드에서처럼 arr이 numpy.ndarray 타입임을 보여줍니다.

[1 2 3 4 5]
<class 'numpy.ndarray'>


- ndarray를 생성하려면 리스트, 튜플 또는 배열과 유사한 객체를 array() 메서드에 전달하면 됩니다. 그러면 ndarray로 변환됩니다.

In [7]:
# 튜플을 사용하여 NumPy 배열을 만듭니다.
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


- 배열의 차원
  - 배열의 차원은 배열 깊이의 한 단계입니다(중첩 배열).
  - 중첩 배열: 배열을 요소로 갖는 배열입니다.

- 0차원 배열
  - 0차원 배열 또는 스칼라는 배열의 요소입니다. 배열의 각 값은 0차원 배열입니다.

In [8]:
# 값이 42인 0차원 배열을 만듭니다.
import numpy as np

arr = np.array(42)

print(arr)

42


- 1차원 배열
  - 0차원 배열을 요소로 갖는 배열을 1차원 배열 또는 1차원 배열이라고 합니다.
  - 이는 가장 일반적이고 기본적인 배열입니다.

In [9]:
# 1,2,3,4,5 값을 포함하는 1차원 배열을 만듭니다.
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


- 2차원 배열
  - 1차원 배열을 요소로 갖는 배열을 2차원 배열이라고 합니다.
  - 2차원 배열은 종종 행렬이나 2차 텐서를 표현하는 데 사용됩니다.
  - NumPy에는 numpy.mat라는 행렬 연산 전용 하위 모듈이 있습니다.

In [11]:
# 1,2,3과 4,5,6 값을 갖는 두 개의 배열을 포함하는 2차원 배열을 만듭니다.
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


- 3차원 배열
  - 2차원 배열(행렬)을 요소로 갖는 배열을 3차원 배열이라고 합니다.
  - 3차원 배열은 종종 3차 텐서를 표현하는 데 사용됩니다.

In [13]:
# 두 개의 2차원 배열을 사용하여 3차원 배열을 생성하고, 두 배열 모두 1, 2, 3과 4, 5, 6의 값을 갖는 두 개의 배열을 포함합니다.
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


- 차원 수 확인?
  - NumPy 배열은 배열의 차원 수를 나타내는 정수를 반환하는 ndim 속성을 제공합니다.

In [14]:
# 배열의 차원 수를 확인하세요.
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


- 고차원 배열
  - 배열은 여러 차원을 가질 수 있습니다.
  - 배열을 생성할 때 ndmin 인수를 사용하여 차원 수를 정의할 수 있습니다.

In [ ]:
# 5차원 배열을 생성하고 차원이 5개인지 확인하세요.
import numpy as np

# 이 배열에서 가장 안쪽 차원(5번째 차원)에는 4개의 요소가 있고, 
# 4번째 차원에는 벡터인 요소가 1개 있고, 
# 3번째 차원에는 벡터가 있는 행렬인 요소가 1개 있고, 
# 2번째 차원에는 3차원 배열인 요소가 1개 있고, 
# 1번째 차원에는 4차원 배열인 요소가 1개 있습니다.
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


- 배열 인덱싱
  - 배열 요소 접근
    - 배열 인덱싱은 배열 요소에 접근하는 것과 같습니다.
    - 배열 요소에 접근하려면 해당 인덱스 번호를 참조해야 합니다.
    - NumPy 배열의 인덱스는 0부터 시작합니다. 즉, 첫 번째 요소의 인덱스는 0이고, 두 번째 요소의 인덱스는 1입니다.

In [16]:
# 다음 배열에서 첫 번째 요소를 가져옵니다.
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr[0])

1


In [17]:
# 다음 배열에서 두 번째 요소를 가져옵니다.
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr[1])

2


In [20]:
# 다음 배열에서 세 번째와 네 번째 요소를 가져와 추가합니다.
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


- 2차원 배열 접근
  - 2차원 배열의 요소에 접근하려면 차원과 인덱스를 나타내는 쉼표로 구분된 정수를 사용할 수 있습니다.
  - 2차원 배열은 행과 열로 구성된 표와 같습니다. 차원은 행을 나타내고 인덱스는 열을 나타냅니다.

In [ ]:
# 첫 번째 행, 두 번째 열의 요소에 접근합니다.
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [ ]:
# 2번째 행, 5번째 열의 요소에 접근합니다.
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


- 3차원 배열 접근
  - 3차원 배열의 요소에 접근하려면 요소의 차원과 인덱스를 나타내는 쉼표로 구분된 정수를 사용할 수 있습니다.

In [23]:
# 첫 번째 배열의 두 번째 배열의 세 번째 요소에 접근합니다.
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


- 위 예제 설명

  - arr[0, 1, 2]는 값 6을 출력합니다.
   ```txt
        이유는 다음과 같습니다.
        첫 번째 숫자는 두 개의 배열을 포함하는 첫 번째 차원을 나타냅니다.
        [[1, 2, 3], [4, 5, 6]]
        그리고:
        [[7, 8, 9], [10, 11, 12]]
        0을 선택했으므로 첫 번째 배열은 다음과 같습니다.
        [[1, 2, 3], [4, 5, 6]]

        두 번째 숫자는 두 번째 차원을 나타내며, 두 번째 배열도 다음과 같습니다.
        [1, 2, 3]
        그리고:
        [4, 5, 6]
        1을 선택했으므로 두 번째 배열은 다음과 같습니다.
        [4, 5, 6]

        세 번째 숫자는 세 개의 값을 포함하는 세 번째 차원을 나타냅니다.
        4
        5
        6

        2를 선택했으므로 세 번째 값은 다음과 같습니다.
        6
    ```

- 음수 인덱싱
  - 음수 인덱싱을 사용하여 배열의 끝에서 접근합니다.

In [25]:
# 두 번째 차원의 마지막 요소를 출력합니다.
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


- 배열 슬라이싱
  - 파이썬에서 슬라이싱은 주어진 인덱스에서 다른 인덱스로 요소를 가져오는 것을 의미합니다.
  - [start:end]와 같이 index 대신 slice를 전달합니다.
  - [start:end:step]과 같이 step을 정의할 수도 있습니다.
  - start를 전달하지 않으면 0으로 간주됩니다.
  - end를 전달하지 않으면 해당 차원의 배열 길이로 간주됩니다.
  - step을 전달하지 않으면 1로 간주됩니다.
  - 참고: 결과에 시작 인덱스는 포함되지만, 끝 인덱스는 제외됩니다.

In [27]:
# 다음 배열에서 인덱스 1부터 인덱스 5까지 요소를 슬라이싱합니다.
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5]) # 결과에 시작 인덱스는 포함되지만, 끝 인덱스는 제외됩니다.

[2 3 4 5]


In [28]:
# 배열의 인덱스 4부터 끝까지 요소를 슬라이스합니다.
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [29]:
# 시작부터 인덱스 4까지 요소를 슬라이스합니다(포함되지 않음)
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


- 음수 슬라이싱
  - 끝에서부터 인덱스를 참조하려면 빼기 연산자를 사용합니다.

In [30]:
# 끝에서 3번째 인덱스부터 끝에서 1번째 인덱스까지 슬라이스합니다.
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


- STEP
  - 단계 값을 사용하여 슬라이싱 단계를 결정합니다.

In [31]:
# 인덱스 1부터 인덱스 5까지 모든 다른 요소를 반환합니다.
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [32]:
# 전체 배열에서 다른 모든 요소를 ​​반환합니다.
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


- 2차원 배열 슬라이싱

In [ ]:
# 두 번째 요소에서 인덱스 1부터 인덱스 4까지의 요소를 슬라이스합니다(포함되지 않음):
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4]) # 참고: 두 번째 요소의 인덱스는 1입니다.

[7 8 9]


In [ ]:
# 두 요소 모두에서 인덱스 2를 반환합니다.
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

# 0:2 (행 선택)
# 슬라이싱(slicing)으로 0번째 행부터 2번째 행 "전"까지 선택
# → 즉, 0행과 1행 (두 행 모두 선택)
print(arr[0:2, 2])

[3 8]


In [35]:
# 두 요소 모두에서 인덱스 1부터 인덱스 4까지(포함되지 않음) 슬라이스하면 2차원 배열이 반환됩니다.
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]
